### ISSUE TITLE
throw new OutputParserException

### ISSUE THREAD

**Issue by tanerdogan** [asanchezyali/talking-avatar-with-ai#1]
Thank you for great sample but when i continue the conversation i am having this issue; I am not React/TS dev, just testing by adding some API keys... Thanks...

```
langchain/dist/output_parsers/structured.js:80
            throw new OutputParserException(`Failed to parse. Text: "${text}". Error: ${e}`, text);
                  ^

OutputParserException [Error]: Failed to parse. Text:
```

**Comment by chenyinlin1** [comment]
> Thank you for great sample but when i continue the conversation i am having this issue; I am not React/TS dev, just testing by adding some API keys... Thanks...
> 
> ```
> langchain/dist/output_parsers/structured.js:80
>             throw new OutputParserException(`Failed to parse. Text: "${text}". Error: ${e}`, text);
>                   ^
> 
> OutputParserException [Error]: Failed to parse. Text:
> ```
Hello. I am trying to reproduce the author's code, but I have found that the repository(git clone  git@github.com :Monadical-SAS/digital-human.git) provided by the author is no longer usable. May I ask if you have downloaded it before? Is it convenient for you to share it?

**Comment by asanchezyali** [comment]
> > Thank you for great sample but when i continue the conversation i am having this issue; I am not React/TS dev, just testing by adding some API keys... Thanks...
> > ```
> > langchain/dist/output_parsers/structured.js:80
> >             throw new OutputParserException(`Failed to parse. Text: "${text}". Error: ${e}`, text);
> >                   ^
> > 
> > OutputParserException [Error]: Failed to parse. Text:
> > ```
> 
> Hello. I am trying to reproduce the author's code, but I have found that the repository(git clone [git@github.com](mailto:git@github.com) :Monadical-SAS/digital-human.git) provided by the author is no longer usable. May I ask if you have downloaded it before? Is it convenient for you to share it?

Hi, I have update the Readme.md. This is the new repository: `git@github.com:asanchezyali/talking-avatar-with-ai.git`
